tenants:
  admin:
    create: false
    project: admin

    apps:
      monitoring:
        path: apps/monitoring/manifests/
        wave: -4
        namespace: monitoring
        extraSourceConfig: |
          directory:
            recurse: true

      opa-gatekeeper:
        path: apps/gatekeeper/
        wave: -4
        namespace: gatekeeper-system
        extraFields: |
          - group: admissionregistration.k8s.io
            kind: ValidatingWebhookConfiguration
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/1/clientConfig/caBundle
            - /webhooks/0/failurePolicy
            - /webhooks/1/failurePolicy
