tenants:
  admin:
    create: false
    project: admin

    apps:
      monitoring:
        path: apps/monitoring
        targetRevision: HEAD
        wave: -5
        extraFields: |
          ignoreDifferences:
          - group: apiextensions.k8s.io
            kind: CustomResourceDefinition
            jsonPointers:
            - /