tenants:
  admin:
    create: false
    project: admin

    apps:
      opa-gatekeeper:
        path: apps/gatekeeper
        wave: -4
        namespace: gatekeeper-system
        extraFields: |
          ignoreDifferences:
          - group: apiextensions.k8s.io
            kind: CustomResourceDefinition
            jsonPointers:
            - /status
          - group: admissionregistration.k8s.io
            kind: ValidatingWebhookConfiguration
            jsonPointers:
            - /webhooks/0/clientConfig/caBundle
            - /webhooks/1/clientConfig/caBundle
            - /webhooks/0/failurePolicy
            - /webhooks/1/failurePolicy
